[config]
"inputs/05.txt" = ["age1yulzyf3c66ndcyww4suwn349syyuur4z72mu82ermvna56vu23ts4fjyjz"]
"inputs/04.txt" = ["age1yulzyf3c66ndcyww4suwn349syyuur4z72mu82ermvna56vu23ts4fjyjz"]
"inputs/03.txt" = ["age1yulzyf3c66ndcyww4suwn349syyuur4z72mu82ermvna56vu23ts4fjyjz"]
"inputs/02.txt" = ["age1yulzyf3c66ndcyww4suwn349syyuur4z72mu82ermvna56vu23ts4fjyjz"]
"inputs/01.txt" = ["age1yulzyf3c66ndcyww4suwn349syyuur4z72mu82ermvna56vu23ts4fjyjz"]
